name: manual approval step testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Check out code
        uses: actions/checkout@v2
      
