name: manual approval step testing

on: 
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

      
      
      - uses: trstringer/manual-approval@v1
        with:
         secret: ${{ github.TOKEN }}
         approvers: SuzanneH7
         minimum-approvals: 1
         #timeout-minutes: 60

      - name: Check out code
        uses: actions/checkout@v2
